export const DO_PAYMENT_INIT = 'stripe/DO_PAYMENT_INIT';
export const DO_PAYMENT_REQUEST = 'stripe/DO_PAYMENT_REQUEST';
export const DO_PAYMENT_SUCCESS = 'stripe/DO_PAYMENT_SUCCESS';
export const DO_PAYMENT_FAILURE = 'stripe/DO_PAYMENT_FAILURE';
export const REGISTER_CARD_REQUEST = 'stripe/REGISTER_CARD_REQUEST';
export const REGISTER_CARD_SUCCESS = 'stripe/REGISTER_CARD_SUCCESS';
export const REGISTER_CARD_FAILURE = 'stripe/REGISTER_CARD_FAILURE';
